/-
The exact git identity of the checkout this worker binary was built from.

A tracked file cannot truthfully contain its own commit, so the value lives in
a one-line artifact generated by the `buildCommit` target in `lakefile.lean`
(which hard-fails when git cannot answer) under the gitignored build
directory. This *module* is tracked so Lake's import scan always resolves it;
only the string it embeds is generated.
-/
namespace Worker.BuildCommit

private def parsed : String × Bool :=
  match (include_str "../.lake/build/build-commit.txt").splitOn " " with
  | [c, "clean"] => (c, false)
  | [c, "dirty"] => (c, true)
  | _ => panic! "malformed build-commit artifact; rebuild with `lake build`"

/-- Commit of the worker source tree at build time (40 hex digits). -/
def commit : String := parsed.1

/-- Whether that tree had uncommitted changes. Recorded, never a build
failure: dev builds must run, and release qualification is what rejects a
dirty tree. -/
def dirty : Bool := parsed.2

end Worker.BuildCommit
