/-
GENERATED by scripts/release_projection.py from release.toml — do not edit.
Tracked because every field is a truthful projection of the authored
contract; the git commit is deliberately absent (see Worker.BuildCommit,
generated at build time by the lakefile's buildCommit target).
-/
namespace Worker.ReleaseInfo

def version : String := "1.1.0"
def pluginApi : Nat := 1
def wireProtocol : Nat := 1
def toolchain : String := "leanprover/lean4:v4.32.0"
def mathlibRev : String := "v4.32.0"

end Worker.ReleaseInfo
