/-
GENERATED by scripts/release_projection.py from release.toml — do not edit.
Thin static release metadata for the worker; wire protocol is what the
adapter compares at startup.
-/
namespace Worker.ReleaseInfo

def version : String := "1.1.0"
def wireProtocol : Nat := 1

end Worker.ReleaseInfo
