"""Typed model of the worker wire protocol.

Pydantic is the type boundary: raw frames (JSON) become these models inside
`WorkerClient`, and nothing above the transport handles untyped dicts. A
malformed worker reply raises ValidationError — a protocol violation is a
crash, not a soft default. Extra fields are ignored (the worker may grow
fields; old clients keep working).

The wire tests (roundtrip.py / test_e2e.py) deliberately do NOT use these
models: they read raw JSON as an independent oracle for the protocol itself.
"""

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, TypeAdapter

Commit = Annotated[str, Field(pattern=r"^[0-9a-f]{40}$")]
PositivePid = Annotated[int, Field(gt=0)]


class _Frame(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    request_id: str | None = None


class Position(BaseModel):
    line: int
    column: int  # Unicode code points, end to end


class Diagnostic(BaseModel):
    severity: Literal["information", "warning", "error"]
    message: str
    start: Position
    end: Position | None = None


class SorryInfo(BaseModel):
    start: Position
    end: Position | None = None
    goal: str


class OutputBundle(BaseModel):
    """A MIME bundle; payload shapes are renderer-owned, not modeled here."""

    data: dict[str, object]
    metadata: dict[str, object] = Field(default_factory=dict)
    display_id: str | None = None


class BuildInfo(BaseModel):
    """The immutable identity of one built artifact: the authored
    compatibility contract (release.toml) plus the exact commit it was built
    from. The adapter's copy is generated by hatch_build.py, the worker's by
    the lakefile's `buildCommit` target; the two must agree on COMPARED before
    any cell runs.

    `mathlib` is reported but never compared: it belongs to the plugin's
    project, not to the adapter/worker pair.
    """

    release: str
    commit: Commit
    dirty: bool
    plugin_api: int
    wire: int
    toolchain: str
    mathlib: str


#: Always compared. These are projections of the authored release.toml, so
#: disagreement is a real incompatibility no matter how either side was built.
STATIC = ("release", "plugin_api", "wire", "toolchain")


def compare(adapter: BuildInfo, worker: BuildInfo) -> tuple[list[str], object]:
    """Decide whether these two artifacts may run together.

    Returns (disagreeing fields, `agreed`). The commit identifies the sources
    only when BOTH trees are clean; a dirty tree's commit proves neither
    agreement nor disagreement, so it is reported verbatim rather than
    enforced. Two CLEAN artifacts built from different commits ARE refused:
    `wire` is not bumped for every frame change, so on one release lineage
    the commit is the only thing separating same-shape semantic skew — the
    exact hazard of the two-pin delivery model, where the adapter comes from
    PyPI/git and the worker from a Lake pin that can name a different commit.

    A pair one rebuild apart is a workflow problem, not a reason to weaken
    this: `just build` refreshes both halves together (see
    scripts/sync_build_info.py), so a refusal means they really did come from
    different sources.
    """
    disagree = [f for f in STATIC if getattr(adapter, f) != getattr(worker, f)]
    unverifiable = adapter.dirty or worker.dirty
    if not unverifiable and adapter.commit != worker.commit:
        disagree.append("commit")
    if disagree:
        return disagree, False
    return [], "unverifiable-dirty" if unverifiable else True


class ReadyFrame(_Frame, BuildInfo):
    op: Literal["ready"]
    protocol: int
    lean: str
    #: The worker process itself — NOT the `lake env` wrapper the client
    #: spawned. Liveness probes must target this pid; the wrapper can outlive
    #: (or lag) the worker and its poll() proves nothing about the worker.
    pid: PositivePid
    snapshot: int


class ExecuteReply(_Frame):
    status: Literal["ok", "error", "cancelled"]
    snapshot: int
    diagnostics: list[Diagnostic] = Field(default_factory=list)
    sorries: list[SorryInfo] = Field(default_factory=list)
    outputs: list[OutputBundle] = Field(default_factory=list)

    def first_error(self, fallback: str = "execution failed") -> str:
        return next((d.message for d in self.diagnostics
                     if d.severity == "error"), fallback)


class WorkerError(_Frame):
    """The worker's generic failure reply for non-execute ops."""

    status: Literal["error"]
    message: str


class CompleteOk(_Frame):
    status: Literal["ok"]
    matches: list[str]
    cursor_start: int
    cursor_end: int


class InspectOk(_Frame):
    status: Literal["ok"]
    found: bool
    hover: str | None = None
    name: str | None = None
    type_: str | None = Field(default=None, alias="type")
    doc: str | None = None


class IsCompleteOk(_Frame):
    status: Literal["ok"]
    result: Literal["complete", "incomplete", "invalid"]


class SaveSessionOk(_Frame):
    status: Literal["ok"]
    saved: bool
    reason: str | None = None


class LoadSessionOk(_Frame):
    status: Literal["ok"]
    snapshot: int


COMPLETE_REPLY: TypeAdapter[CompleteOk | WorkerError] = TypeAdapter(
    Annotated[CompleteOk | WorkerError, Field(discriminator="status")])
INSPECT_REPLY: TypeAdapter[InspectOk | WorkerError] = TypeAdapter(
    Annotated[InspectOk | WorkerError, Field(discriminator="status")])
IS_COMPLETE_REPLY: TypeAdapter[IsCompleteOk | WorkerError] = TypeAdapter(
    Annotated[IsCompleteOk | WorkerError, Field(discriminator="status")])
SAVE_SESSION_REPLY: TypeAdapter[SaveSessionOk | WorkerError] = TypeAdapter(
    Annotated[SaveSessionOk | WorkerError, Field(discriminator="status")])
LOAD_SESSION_REPLY: TypeAdapter[LoadSessionOk | WorkerError] = TypeAdapter(
    Annotated[LoadSessionOk | WorkerError, Field(discriminator="status")])


# -- ipykernel ingestion boundary -------------------------------------------
# ipykernel hands handlers untyped message dicts; these models re-type that
# dependency at the door (POLICY.NO_UNTYPED_IMPORT_LEAK). Only the fields the
# kernel reads are modeled; the rest is ignored.

class CommContent(BaseModel):
    comm_id: str
    target_name: str | None = None
    data: object = None


class CommParent(BaseModel):
    content: CommContent


# -- kernel-side document model (frontend comm boundary) --------------------

class DocCell(BaseModel):
    id: str
    source: str


class DocumentMessage(BaseModel):
    type: Literal["document"]
    cells: list[DocCell]


class CellState(BaseModel):
    """Committed execution state of one notebook cell."""

    source: str
    snapshot: int
    parent: int
