#!/usr/bin/env python3
"""Check/update version and toolchain fields from release.toml.

write  — rewrite projections in place
check  — fail if any projection drifted
"""

from __future__ import annotations

import difflib
import json
import re
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MATHLIB_URL = "https://github.com/leanprover-community/mathlib4.git"


def load_release(root: Path) -> dict[str, str | int]:
    raw = tomllib.loads((root / "release.toml").read_text())
    if raw.get("schema") != 1:
        sys.exit(f"release.toml: unknown schema {raw.get('schema')!r}")
    return {
        "version": raw["release"]["version"],
        "lean": raw["toolchain"]["lean"],
        "mathlib": raw["toolchain"]["mathlib"],
        "mathlib_commit": raw["toolchain"]["mathlib_commit"],
        "wire_protocol": raw["compat"]["wire_protocol"],
    }


def sub_once(pattern: str, repl: str, text: str, where: str) -> str:
    out, n = re.subn(pattern, repl, text, flags=re.M)
    if n != 1:
        sys.exit(f"{where}: expected one match for {pattern!r}, found {n}")
    return out


def project(root: Path, rel: dict[str, str | int]) -> dict[Path, str]:
    out: dict[Path, str] = {}
    p = Path("worker/lakefile.lean")
    out[p] = sub_once(
        r'(version := v!")[^"]+(")', rf"\g<1>{rel['version']}\g<2>",
        (root / p).read_text(), str(p))
    p = Path("dsls/nbdsl/lakefile.lean")
    text = sub_once(
        r'(version := v!")[^"]+(")', rf"\g<1>{rel['version']}\g<2>",
        (root / p).read_text(), str(p))
    out[p] = sub_once(
        r'("https://github\.com/leanprover-community/mathlib4\.git" @ ")[^"]+(")',
        rf"\g<1>{rel['mathlib']}\g<2>", text, str(p))
    p = Path("nbdsl_kernel/pyproject.toml")
    out[p] = sub_once(
        r'^(version = ")[^"]+(")$', rf"\g<1>{rel['version']}\g<2>",
        (root / p).read_text(), str(p))
    p = Path("jupyterlab_nbdsl/package.json")
    out[p] = sub_once(
        r'^(  "version": ")[^"]+(",)$', rf"\g<1>{rel['version']}\g<2>",
        (root / p).read_text(), str(p))
    for p in (Path("worker/lean-toolchain"), Path("dsls/nbdsl/lean-toolchain")):
        out[p] = f"{rel['lean']}\n"
    out[Path("worker/Worker/ReleaseInfo.lean")] = (
        f'''/-
GENERATED by scripts/release_projection.py from release.toml — do not edit.
-/
namespace Worker.ReleaseInfo

def version : String := "{rel['version']}"
def wireProtocol : Nat := {rel['wire_protocol']}

end Worker.ReleaseInfo
'''
    )
    return out


def mathlib_ok(root: Path, rel: dict[str, str | int]) -> bool:
    pkgs = json.loads((root / "dsls/nbdsl/lake-manifest.json").read_text())["packages"]
    matches = [p for p in pkgs if isinstance(p, dict) and p.get("name") == "mathlib"]
    if len(matches) != 1:
        return False
    p = matches[0]
    return (p.get("type") == "git" and p.get("url") == MATHLIB_URL
            and p.get("inputRev") == rel["mathlib"]
            and p.get("rev") == rel["mathlib_commit"])


def write_mathlib(root: Path, rel: dict[str, str | int]) -> None:
    path = root / "dsls/nbdsl/lake-manifest.json"
    manifest = json.loads(path.read_text())
    for package in manifest["packages"]:
        if isinstance(package, dict) and package.get("name") == "mathlib":
            package["inputRev"] = rel["mathlib"]
            package["rev"] = rel["mathlib_commit"]
            break
    else:
        sys.exit("lake-manifest.json: mathlib package missing")
    path.write_text(json.dumps(manifest, indent=2) + "\n")


def write(root: Path) -> None:
    rel = load_release(root)
    for path, content in project(root, rel).items():
        (root / path).write_text(content)
        print(f"projected {path}")
    write_mathlib(root, rel)
    print("projected dsls/nbdsl/lake-manifest.json")


def check(root: Path) -> int:
    rel = load_release(root)
    failures = 0
    for path, content in project(root, rel).items():
        actual = (root / path).read_text() if (root / path).exists() else ""
        if actual != content:
            failures += 1
            print("\n".join(difflib.unified_diff(
                actual.splitlines(), content.splitlines(),
                fromfile=str(path), tofile="projection", lineterm="")))
    if not mathlib_ok(root, rel):
        failures += 1
        print("PROJECTION DRIFT: mathlib lock disagrees with release.toml")
    if failures:
        print(f"PROJECTION DRIFT: {failures} disagreement(s)")
        return 1
    print("all projections agree with release.toml")
    return 0


def main() -> None:
    args = sys.argv[1:]
    root = REPO
    if "--root" in args:
        i = args.index("--root")
        root = Path(args[i + 1]).resolve()
        del args[i:i + 2]
    if args == ["write"]:
        write(root)
    elif args == ["check"]:
        sys.exit(check(root))
    else:
        sys.exit(__doc__)


if __name__ == "__main__":
    main()
