#!/usr/bin/env python3
"""Release projection tool — the one-way derivation from release.toml.

`release.toml` is the only authored static compatibility source. This tool
owns every tool-specific version/toolchain declaration as a generated
projection of it:

  write     rewrite all projections in place from release.toml
  check     regenerate to a temporary tree and fail on any diff
  selftest  prove check rejects a deliberately mutated projection
            (mutates a temporary copy, never the authoritative files)

Projected files:
  worker/lakefile.lean                  package version
  dsls/nbdsl/lakefile.lean              package version + mathlib revision
  nbdsl_kernel/pyproject.toml           distribution version
  jupyterlab_nbdsl/package.json         npm version (Python metadata reads
                                        this via hatch-nodejs-version)
  worker/lean-toolchain                 Lean toolchain identity
  dsls/nbdsl/lean-toolchain             Lean toolchain identity
  worker/Worker/ReleaseInfo.lean        tracked static build-info constants
"""

from __future__ import annotations

import difflib
import re
import shutil
import subprocess
import sys
import tempfile
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def load_release(root: Path) -> dict[str, str | int]:
    raw = tomllib.loads((root / "release.toml").read_text())
    if raw.get("schema") != 1:
        sys.exit(f"release.toml: unknown schema {raw.get('schema')!r}")
    flat = {
        "version": raw["release"]["version"],
        "lean": raw["toolchain"]["lean"],
        "mathlib": raw["toolchain"]["mathlib"],
        "plugin_api": raw["compat"]["plugin_api"],
        "wire_protocol": raw["compat"]["wire_protocol"],
    }
    if not re.fullmatch(r"\d+\.\d+\.\d+", str(flat["version"])):
        sys.exit(f"release.toml: malformed release.version {flat['version']!r}")
    for key in ("plugin_api", "wire_protocol"):
        if not isinstance(flat[key], int):
            sys.exit(f"release.toml: compat.{key} must be an integer")
    return flat


def sub_once(pattern: str, repl: str, text: str, where: str) -> str:
    out, n = re.subn(pattern, repl, text, flags=re.M)
    if n != 1:
        sys.exit(f"{where}: expected exactly one match for {pattern!r}, found {n}")
    return out


def release_info_lean(rel: dict[str, str | int]) -> str:
    return f'''/-
GENERATED by scripts/release_projection.py from release.toml — do not edit.
Tracked because every field is a truthful projection of the authored
contract; the git commit is deliberately absent (see Worker.BuildCommit,
generated at build time by the lakefile's buildCommit target).
-/
namespace Worker.ReleaseInfo

def version : String := "{rel['version']}"
def pluginApi : Nat := {rel['plugin_api']}
def wireProtocol : Nat := {rel['wire_protocol']}
def toolchain : String := "{rel['lean']}"
def mathlibRev : String := "{rel['mathlib']}"

end Worker.ReleaseInfo
'''


def project(root: Path, rel: dict[str, str | int]) -> dict[Path, str]:
    """Return {relative path: projected content} for every owned file."""
    out: dict[Path, str] = {}

    p = Path("worker/lakefile.lean")
    out[p] = sub_once(
        r'(version := v!")[^"]+(")', rf"\g<1>{rel['version']}\g<2>",
        (root / p).read_text(), str(p))

    p = Path("dsls/nbdsl/lakefile.lean")
    text = sub_once(
        r'(version := v!")[^"]+(")', rf"\g<1>{rel['version']}\g<2>",
        (root / p).read_text(), str(p))
    out[p] = sub_once(
        r'("https://github\.com/leanprover-community/mathlib4\.git" @ ")[^"]+(")',
        rf"\g<1>{rel['mathlib']}\g<2>", text, str(p))

    p = Path("nbdsl_kernel/pyproject.toml")
    out[p] = sub_once(
        r'^(version = ")[^"]+(")$', rf"\g<1>{rel['version']}\g<2>",
        (root / p).read_text(), str(p))

    p = Path("jupyterlab_nbdsl/package.json")
    out[p] = sub_once(
        r'^(  "version": ")[^"]+(",)$', rf"\g<1>{rel['version']}\g<2>",
        (root / p).read_text(), str(p))

    for p in (Path("worker/lean-toolchain"), Path("dsls/nbdsl/lean-toolchain")):
        out[p] = f"{rel['lean']}\n"

    out[Path("worker/Worker/ReleaseInfo.lean")] = release_info_lean(rel)
    return out


def write(root: Path) -> None:
    for path, content in project(root, load_release(root)).items():
        (root / path).write_text(content)
        print(f"projected {path}")


def check(root: Path) -> int:
    failures = 0
    with tempfile.TemporaryDirectory(prefix="release-projection-") as tmp:
        for path, content in project(root, load_release(root)).items():
            staged = Path(tmp) / path  # the temporary tree
            staged.parent.mkdir(parents=True, exist_ok=True)
            staged.write_text(content)
            actual = (root / path).read_text() if (root / path).exists() else ""
            if actual != content:
                failures += 1
                diff = difflib.unified_diff(
                    actual.splitlines(), content.splitlines(),
                    fromfile=f"{path} (working tree)",
                    tofile=f"{path} (projection of release.toml)", lineterm="")
                print("\n".join(diff))
    if failures:
        print(f"PROJECTION DRIFT: {failures} file(s) disagree with release.toml")
        return 1
    print("all projections agree with release.toml")
    return 0


def selftest(root: Path) -> int:
    with tempfile.TemporaryDirectory(prefix="release-selftest-") as tmp:
        copy = Path(tmp) / "repo"
        for path in [Path("release.toml"), *project(root, load_release(root))]:
            (copy / path).parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(root / path, copy / path)
        if check(copy) != 0:
            print("selftest: baseline copy unexpectedly drifted", file=sys.stderr)
            return 1
        victim = copy / "nbdsl_kernel/pyproject.toml"
        victim.write_text(victim.read_text().replace(
            'version = "', 'version = "9.9.9-mutated', 1))
        proc = subprocess.run(
            [sys.executable, __file__, "check", "--root", str(copy)],
            capture_output=True, text=True)
        if proc.returncode == 0:
            print("selftest FAILED: check accepted a mutated governed version")
            return 1
        print("selftest: check rejects a mutated governed version")
        return 0


def main() -> None:
    args = sys.argv[1:]
    root = REPO
    if "--root" in args:
        i = args.index("--root")
        root = Path(args[i + 1]).resolve()
        del args[i:i + 2]
    if args == ["write"]:
        write(root)
    elif args == ["check"]:
        sys.exit(check(root))
    elif args == ["selftest"]:
        sys.exit(selftest(root))
    else:
        sys.exit(__doc__)


if __name__ == "__main__":
    main()
