#!/usr/bin/env python3
"""Check/update version and toolchain fields from release.toml.

write  — rewrite projections in place
check  — fail if any projection drifted

Mathlib's resolved lockfile is owned by Lake (``lake update``), not this script.
``compat.wire_protocol`` is owned by ``Worker.Protocol.wireProtocol``; this
script only verifies agreement with release.toml.
"""

from __future__ import annotations

import difflib
import re
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def load_release(root: Path) -> dict[str, str | int]:
    raw = tomllib.loads((root / "release.toml").read_text())
    if raw.get("schema") != 1:
        sys.exit(f"release.toml: unknown schema {raw.get('schema')!r}")
    return {
        "version": raw["release"]["version"],
        "lean": raw["toolchain"]["lean"],
        "mathlib": raw["toolchain"]["mathlib"],
        "wire_protocol": raw["compat"]["wire_protocol"],
    }


def sub_once(pattern: str, repl: str, text: str, where: str) -> str:
    out, n = re.subn(pattern, repl, text, flags=re.M)
    if n != 1:
        sys.exit(f"{where}: expected one match for {pattern!r}, found {n}")
    return out


def project(root: Path, rel: dict[str, str | int]) -> dict[Path, str]:
    out: dict[Path, str] = {}
    p = Path("worker/lakefile.lean")
    out[p] = sub_once(
        r'(version := v!")[^"]+(")', rf"\g<1>{rel['version']}\g<2>",
        (root / p).read_text(), str(p))
    p = Path("dsls/nbdsl/lakefile.lean")
    text = sub_once(
        r'(version := v!")[^"]+(")', rf"\g<1>{rel['version']}\g<2>",
        (root / p).read_text(), str(p))
    out[p] = sub_once(
        r'("https://github\.com/leanprover-community/mathlib4\.git" @ ")[^"]+(")',
        rf"\g<1>{rel['mathlib']}\g<2>", text, str(p))
    p = Path("nbdsl_kernel/pyproject.toml")
    out[p] = sub_once(
        r'^(version = ")[^"]+(")$', rf"\g<1>{rel['version']}\g<2>",
        (root / p).read_text(), str(p))
    p = Path("jupyterlab_nbdsl/package.json")
    out[p] = sub_once(
        r'^(  "version": ")[^"]+(",)$', rf"\g<1>{rel['version']}\g<2>",
        (root / p).read_text(), str(p))
    for p in (Path("worker/lean-toolchain"), Path("dsls/nbdsl/lean-toolchain")):
        out[p] = f"{rel['lean']}\n"
    out[Path("worker/Worker/ReleaseInfo.lean")] = (
        f'''/-
GENERATED by scripts/release_projection.py from release.toml — do not edit.
-/
namespace Worker.ReleaseInfo

def version : String := "{rel['version']}"

end Worker.ReleaseInfo
'''
    )
    return out


def wire_ok(root: Path, rel: dict[str, str | int]) -> bool:
    text = (root / "worker/Worker/Protocol.lean").read_text()
    return bool(re.search(
        rf"^def wireProtocol : Nat := {rel['wire_protocol']}$", text, re.M))


def write(root: Path) -> None:
    rel = load_release(root)
    for path, content in project(root, rel).items():
        (root / path).write_text(content)
        print(f"projected {path}")
    if not wire_ok(root, rel):
        sys.exit(
            "Worker.Protocol.wireProtocol disagrees with "
            "release.toml compat.wire_protocol — edit Protocol.lean")


def check(root: Path) -> int:
    rel = load_release(root)
    failures = 0
    for path, content in project(root, rel).items():
        actual = (root / path).read_text() if (root / path).exists() else ""
        if actual != content:
            failures += 1
            print("\n".join(difflib.unified_diff(
                actual.splitlines(), content.splitlines(),
                fromfile=str(path), tofile="projection", lineterm="")))
    if not wire_ok(root, rel):
        failures += 1
        print("PROJECTION DRIFT: Protocol.wireProtocol vs release.toml")
    if failures:
        print(f"PROJECTION DRIFT: {failures} disagreement(s)")
        return 1
    print("all projections agree with release.toml")
    return 0


def main() -> None:
    args = sys.argv[1:]
    root = REPO
    if "--root" in args:
        i = args.index("--root")
        root = Path(args[i + 1]).resolve()
        del args[i:i + 2]
    if args == ["write"]:
        write(root)
    elif args == ["check"]:
        sys.exit(check(root))
    else:
        sys.exit(__doc__)


if __name__ == "__main__":
    main()
